apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-audio-to-text2-aug1 
  janus-idp.io/tekton: test-audio-to-text2-aug1
  backstage.io/kubernetes-id: test-audio-to-text2-aug1
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: test-audio-to-text2-aug1
resources: 
- application-dev.yaml